server:
  port: 8080                # Spring Boot 애플리케이션이 사용할 포트 번호
  address: 0.0.0.0          # 외부 네트워크에서도 접근 가능하도록 설정

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}
