name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker 로그인 (GitHub Packages를 사용하는 경우)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build -t <YourDockerHubUsername>/s3imageupload:latest .
          docker push <YourDockerHubUsername>/s3imageupload:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # SSH를 사용해 EC2에 접속하여 Docker 컨테이너 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull <YourDockerHubUsername>/s3imageupload:latest
            docker stop s3imageupload || true
            docker rm s3imageupload || true
            docker run -d --name s3imageupload -p 8080:8080 <YourDockerHubUsername>/s3imageupload:latest
