name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      # JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # 의존성 설치 및 빌드
      - name: Build with Gradle
        run: |
            ./gradlew clean build  
        

      # Docker 로그인 (DockerHub에 로그인)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build -t xoo1228/s3imageupload:latest .
          docker push xoo1228/s3imageupload:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # SSH를 사용해 EC2에 접속하여 Docker 컨테이너 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull xoo1228/s3imageupload:latest
            docker stop s3imageupload || true
            docker rm s3imageupload || true
            docker run -d --name s3imageupload -p 8080:8080 xoo1228/s3imageupload:latest
